#!/usr/bin/env bash
set -euo pipefail

MARKER_FILE="/workspace/.musubi_bootstrap_done"
MUSUBI_ENV_FILE="/workspace/scripts/musubi_env.sh"
export UV_CACHE_DIR="${UV_CACHE_DIR:-/workspace/.cache/uv}"
export UV_LINK_MODE="${UV_LINK_MODE:-hardlink}"

if [[ -f "${MARKER_FILE}" ]]; then
  echo "[bootstrap] Already initialized. Skipping."
  exit 0
fi

echo "[bootstrap] Initializing workspace and software"

mkdir -p \
  /workspace/models/dit \
  /workspace/models/vae \
  /workspace/models/text_encoder \
  /workspace/dataset/images \
  /workspace/dataset/cache/latents \
  /workspace/dataset/cache/text_encoder \
  /workspace/output \
  /workspace/logs \
  /workspace/scripts \
  /workspace/notebooks \
  /workspace/.cache/huggingface \
  "${UV_CACHE_DIR}"

if [[ ! -d /workspace/musubi-tuner ]]; then
  echo "[bootstrap] Cloning musubi-tuner"
  git clone --recursive https://github.com/kohya-ss/musubi-tuner.git /workspace/musubi-tuner
else
  echo "[bootstrap] musubi-tuner exists, syncing submodules"
  git -C /workspace/musubi-tuner submodule update --init --recursive
fi

echo "[bootstrap] Installing musubi-tuner dependencies with uv"
cd /workspace/musubi-tuner

# Avoid leaking global venv into uv project env resolution.
unset VIRTUAL_ENV || true

MUSUBI_PYTHON="${MUSUBI_PYTHON:-3.10}"
MUSUBI_CUDA_EXTRA="${MUSUBI_CUDA_EXTRA:-cu128}"
MUSUBI_TORCH_VERSION="${MUSUBI_TORCH_VERSION:-2.9.1}"
MUSUBI_TORCHVISION_VERSION="${MUSUBI_TORCHVISION_VERSION:-0.24.1}"
MUSUBI_TORCHAUDIO_VERSION="${MUSUBI_TORCHAUDIO_VERSION:-${MUSUBI_TORCH_VERSION}}"
MUSUBI_TORCH_PIN="${MUSUBI_TORCH_PIN:-auto}"
BOOTSTRAP_NET_RETRIES="${BOOTSTRAP_NET_RETRIES:-5}"
BOOTSTRAP_NET_RETRY_DELAY="${BOOTSTRAP_NET_RETRY_DELAY:-20}"

run_with_retries() {
  local label="$1"
  shift
  local attempt=1

  until "$@"; do
    local status=$?
    if (( attempt >= BOOTSTRAP_NET_RETRIES )); then
      echo "[bootstrap] ${label} failed after ${attempt} attempts"
      return "${status}"
    fi
    echo "[bootstrap] ${label} failed on attempt ${attempt}/${BOOTSTRAP_NET_RETRIES}; retrying in ${BOOTSTRAP_NET_RETRY_DELAY}s"
    sleep "${BOOTSTRAP_NET_RETRY_DELAY}"
    attempt=$((attempt + 1))
  done
}

write_musubi_env() {
  local cuda_lib_path
  cuda_lib_path="$(
    uv run python - <<'PY'
import pathlib
import site
import sysconfig

roots = []
purelib = sysconfig.get_paths().get("purelib")
if purelib:
    roots.append(pathlib.Path(purelib))
for item in site.getsitepackages():
    path = pathlib.Path(item)
    if path not in roots:
        roots.append(path)

paths = []
for root in roots:
    for pattern in ("nvidia/*/lib", "torch/lib"):
        for path in root.glob(pattern):
            if path.is_dir():
                text = str(path)
                if text not in paths:
                    paths.append(text)

print(":".join(paths))
PY
  )"

  mkdir -p "$(dirname "${MUSUBI_ENV_FILE}")"
  {
    echo "# Generated by bootstrap.sh. Source this before running musubi-tuner commands."
    echo "export UV_CACHE_DIR=\"\${UV_CACHE_DIR:-${UV_CACHE_DIR}}\""
    echo "export UV_LINK_MODE=\"\${UV_LINK_MODE:-hardlink}\""
    if [[ -n "${cuda_lib_path}" ]]; then
      echo "export LD_LIBRARY_PATH=\"${cuda_lib_path}\${LD_LIBRARY_PATH:+:\${LD_LIBRARY_PATH}}\""
    fi
  } > "${MUSUBI_ENV_FILE}"

  # shellcheck disable=SC1090
  source "${MUSUBI_ENV_FILE}"
}

verify_torch() {
  local label="$1"
  echo "[bootstrap] musubi torch/CUDA ${label}:"
  uv run python -c "import torch; print('torch', torch.__version__, 'cuda', torch.version.cuda)"
}

install_if_missing() {
  local import_name="$1"
  local package_name="$2"

  if uv run python -c "import ${import_name}" >/dev/null 2>&1; then
    echo "[bootstrap] ${package_name} already available in musubi env"
    return 0
  fi

  echo "[bootstrap] Installing ${package_name} in musubi-tuner environment (best-effort)"
  run_with_retries "${package_name} install" uv pip install "${package_name}" || \
    echo "[bootstrap] ${package_name} install failed in musubi env; related features may be unavailable."
}

echo "[bootstrap] uv sync with Python ${MUSUBI_PYTHON} and extra ${MUSUBI_CUDA_EXTRA}"
if ! run_with_retries "uv sync --extra ${MUSUBI_CUDA_EXTRA}" uv sync --python "${MUSUBI_PYTHON}" --extra "${MUSUBI_CUDA_EXTRA}"; then
  echo "[bootstrap] uv sync failed with extra ${MUSUBI_CUDA_EXTRA}, retrying without CUDA extra"
  run_with_retries "uv sync" uv sync --python "${MUSUBI_PYTHON}"
fi

write_musubi_env

echo "[bootstrap] musubi environment Python version:"
uv run python -V
TORCH_OK=0
if verify_torch "after uv sync"; then
  TORCH_OK=1
else
  echo "[bootstrap] Torch import failed after uv sync; attempting explicit torch stack repair."
fi

PIN_TORCH=0
case "${MUSUBI_TORCH_PIN,,}" in
  1|true|yes|always|force)
    PIN_TORCH=1
    ;;
  0|false|no|never|skip)
    PIN_TORCH=0
    ;;
  auto)
    if (( TORCH_OK == 0 )); then
      PIN_TORCH=1
    fi
    ;;
  *)
    echo "[bootstrap] Unknown MUSUBI_TORCH_PIN=${MUSUBI_TORCH_PIN}; using auto behavior"
    if (( TORCH_OK == 0 )); then
      PIN_TORCH=1
    fi
    ;;
esac

if (( PIN_TORCH == 1 )); then
  echo "[bootstrap] Pinning torch stack in musubi env: torch==${MUSUBI_TORCH_VERSION}, torchvision==${MUSUBI_TORCHVISION_VERSION}, torchaudio==${MUSUBI_TORCHAUDIO_VERSION} (${MUSUBI_CUDA_EXTRA})"
  TORCH_INDEX_URL="https://download.pytorch.org/whl/${MUSUBI_CUDA_EXTRA}"
  run_with_retries "torch stack pin" uv pip install \
    --index-url "${TORCH_INDEX_URL}" \
    --extra-index-url https://pypi.org/simple \
    "torch==${MUSUBI_TORCH_VERSION}" \
    "torchvision==${MUSUBI_TORCHVISION_VERSION}" \
    "torchaudio==${MUSUBI_TORCHAUDIO_VERSION}" || \
    echo "[bootstrap] Torch pinning failed; continuing with uv-resolved torch version."
else
  echo "[bootstrap] MUSUBI_TORCH_PIN=${MUSUBI_TORCH_PIN}; keeping uv-resolved torch stack"
fi

write_musubi_env
if ! verify_torch "after torch setup"; then
  echo "[bootstrap] ERROR: torch cannot be imported after torch setup."
  echo "[bootstrap] If the uv-resolved torch failed, set MUSUBI_TORCH_PIN=always to force the configured torch stack."
  echo "[bootstrap] If a forced pin fails, try MUSUBI_TORCH_PIN=never to keep musubi's resolved torch stack."
  exit 1
fi

echo "[bootstrap] Installing requested flash_attn wheel in musubi-tuner environment"
if uv run python -c "import sys; exit(0 if sys.version_info[:2] == (3, 12) else 1)"; then
  run_with_retries "flash_attn install" uv pip install --no-cache-dir \
    "https://github.com/Dao-AILab/flash-attention/releases/download/v2.8.3/flash_attn-2.8.3+cu12torch2.9cxx11abiTRUE-cp312-cp312-linux_x86_64.whl" || \
    echo "[bootstrap] flash_attn wheel install failed in musubi env; continuing."
else
  echo "[bootstrap] Skipping requested cp312 flash_attn wheel because musubi env is not Python 3.12."
fi

install_if_missing bitsandbytes bitsandbytes
install_if_missing hf_transfer hf_transfer
install_if_missing prodigyopt prodigyopt

echo "[bootstrap] Writing non-interactive accelerate config"
mkdir -p /root/.cache/huggingface/accelerate
cat > /root/.cache/huggingface/accelerate/default_config.yaml << 'EOF'
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: 'NO'
downcast_bf16: 'no'
enable_cpu_affinity: false
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
EOF

echo "[bootstrap] Staging helper scripts and templates into /workspace/scripts"
cp -f /opt/runpod/download_models.sh /workspace/scripts/download_models.sh
cp -f /opt/runpod/prepare_dataset.sh /workspace/scripts/prepare_dataset.sh
cp -f /opt/runpod/train_lora_prodigy.sh /workspace/scripts/train_lora_prodigy.sh
cp -f /opt/runpod/train_lora_adamw8bit.sh /workspace/scripts/train_lora_adamw8bit.sh
cp -f /opt/runpod/convert_lora.sh /workspace/scripts/convert_lora.sh
cp -f /opt/runpod/start_tensorboard.sh /workspace/scripts/start_tensorboard.sh
chmod +x /workspace/scripts/*.sh

if [[ ! -f /workspace/dataset/dataset.toml ]]; then
  cp /opt/runpod/dataset.toml.example /workspace/dataset/dataset.toml
fi
if [[ ! -f /workspace/dataset/sample_prompts.txt ]]; then
  cp /opt/runpod/sample_prompts.txt /workspace/dataset/sample_prompts.txt
fi

cp --update=none /opt/runpod/notebooks/00_musubi_tuner_runpod.ipynb /workspace/notebooks/00_musubi_tuner_runpod.ipynb || true

if [[ "${SKIP_MODEL_DOWNLOAD:-0}" != "1" ]]; then
  /workspace/scripts/download_models.sh
else
  echo "[bootstrap] SKIP_MODEL_DOWNLOAD=1 -> skipping model download"
fi

touch "${MARKER_FILE}"
echo "[bootstrap] Completed successfully"
